name: verify

on: push

jobs:
  generate_includes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Generate include files
      run: |
        cd _includes
        python3 generate.py
