name: verify

on: push

jobs:
  generate_includes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Generate include files
      run: |
        cd _includes
        python3 generate.py

    - name: Commit and push
      run: |
        git add -N .
        if ! git diff --exit-code --quiet
        then
          git config user.name "KodamaD"
          git config user.email "kodkodaman@gmail.com"
          git add .
          git commit -m "generate include files"
          git pull
          git push -u origin main
        fi
